### ISSUE TITLE
Fix role text in right navbar

### ISSUE THREAD

**Issue by taha-ghadirian** [drit-group/MisProject#37]
Right navbar (Under name) should show highest role title, 
Currently it's a default `مدیر اداری` value for everyone.

**Comment by AmirHoseinRahmati23** [comment]
leave it to me

**Comment by taha-ghadirian** [comment]
Hello @AmirHoseinRahmati23, 
Thanks for accepting this issue. 

Here is an step by step help for you:
1. Fork project
2. If project is already forked, please make sure it's in the latest version (In github fork and local repo).
3. Created new branch based on `AdminPanel` named `RoleTextNavBar` and work on it. 
4. Start with core layer, add required method to `IUserService` named `GetHighestRole` that returns `RoleDto`. It should return highest role based on role `priority`.
5. Create `GetMyHighestRole` in `UserController`, make sure user is validated (You can take a look in other methods in this controller)
6. Add method to `HttpCallers` in `CliendLibraries` layer, in `IUserCaller`.
7. Go to navbar and call your method for getting highest role and show it to user.
8. You're all done, commit and make PR (To `Panel` branch`).
